### ISSUE TITLE
White browser page

### ISSUE THREAD

**Issue by easiers** [innocenat/typingmania#8]
I am trying to get TypingMania working but when i run the .html files I just get greeted with a white screen. I am not too sure what I have been doing wrong. I went to releases and downloaded the .zip for the latest version I run index.html but it's just a white screen. Is there something I am missing?

**Comment by innocenat** [comment]
Apparently I was not up to date with how browser these day do security. The mechanism used in the game is apparently blocked if runs directly from the file system. So you need some kind of web server to run it.

I will try to see if I can fix  this problem, but no guarantee sorry.

In the mean time, you can add custom song file to any running game, so you can try to use https://typingmania.stdlib.xyz/engine/ (which doesn't contain any song) and just add your own file.

Sorry for the inconvenience.

**Comment by innocenat** [comment]
I just checked, and it's near impossible to make the game work locally without some drastic change. Sorry.

**Comment by easiers** [comment]
> I just checked, and it's near impossible to make the game work locally without some drastic change. Sorry.

Yeah that is perfectly fine, I just figured it out right now. Wish I saw this but I forgot to refresh. Anyways thanks for the reply and thanks for the amazing project you made!
